# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.36.1
# 

Name:       harbour-lonewolf

# >> macros
%bcond_with harbour
# << macros
%define pkgname %{name}
%define lw_minver 0.1.250729
%define plugindir %{_datadir}/%{name}/
%define fontdir %{_datadir}/%{name}/fonts
%define __requires_exclude_from ^%{_datadir}/%{name}/_cheat/.*\.sh$
%define __provides_exclude ^(font|qml).*$
%define __provides_exclude_from %{plugindir}

Summary:    A role-playing choose-your-own-adventure game
Version:    0.1.260901
Release:    0
Group:      Applications
License:    GPLv3 and OFL
URL:        https://github.com/nephros/lonewolf
Source0:    %{name}-%{version}.tar.gz
Source1:    lonewolf-app-icon.svg
Source2:    %{name}.profile
Source3:    Alegreya-Medium.otf
Source4:    Alegreya-Regular.otf
Source5:    https://github.com/undercasetype/Fraunces/raw/1.000/fonts/static/otf/Fraunces9ptSuperSoft-Regular.otf
Source6:    savescumming.sh
Source100:  harbour-lonewolf.yaml
Requires:   libsailfishapp-launcher
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5XmlPatterns)
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(glesv2)
BuildRequires:  pkgconfig(icu-i18n)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  sailfish-svg2png
BuildRequires:  qml-rpm-macros
BuildRequires:  cmake
BuildRequires:  gettext
BuildRequires:  intltool
BuildRequires:  desktop-file-utils
BuildRequires:  cmake

%description
%{summary}.

Lone Wolf is a role-playing book series from the 80s.

You are the sole survivor of a devastating attack on the monastery where
you were learning the skills of the Kai Lords. You swear vengeance on the
Darklords for the massacre of the Kai warriors, and with a sudden flash of
insight you know what you must do. You must set off on a perilous journey
to the capital city to warn the King of the terrible threat that faces his
people: For you are now the last of the Kai.

You are now Lone Wolf.

This App is a port of Tim Süberkrüb's Qt/QML version, which is a port of
the original Lone Wolf app for Ubuntu Phone by Michael Terry.

%if 0%{?_chum}
Title: Lonewolf
Type: desktop-application
DeveloperName: Peter G., Tim Süberkrüb, Michael Terry
PackagedBy: nephros
Categories:
 - Games
Custom:
  Repo: https://github.com/nephros/lonewolf
PackageIcon: %{url}/raw/sfos/rpm/lonewolf-app-icon.svg
Screenshots:
  - %{url}/raw/sfos/Screenshot_001.jpg
  - %{url}/raw/sfos/Screenshot_002.jpg
Links:
  Help: https://www.projectaon.org/en/ReadersHandbook/Home
%endif


%package tts-plugin
Summary:    Text-to-Speech support for %{name}
Group:      Games
BuildArch:  noarch
Requires:   harbour-dsnote >= 4.7.0
Requires:   %{name} >= %{lw_minver}

%description tts-plugin
Adds text-to-speech support to the Lone Wolf app from Jolla Store (Harbour).

Requires the excellent Speech Note (harbour-dsnote) by mkiol.
This means you have to have the Openrepos (Storeman) mkiol repo enabled in
order to install this.

The plugin will use engine and settings configured for English (in Speech Note settings).

%if "0%{?_chum}"
Title: TTS plugin for Lone Wolf
Type: desktop-application
Categories:
 - Games
PackageIcon: %{url}/raw/sfos/rpm/lonewolf-app-icon.svg
Screenshots:
 - https://github.com/nephros/harbour-lonewolf/raw/sfos/Screenshot_004.jpg
%endif


%define please_also ignore this macro
%if 0%{?sailfishos_version} < 40600
%if 0%{?sailfishos_version} <= 40001
%define cmake_build %__cmake --build "."
%define cmake_install %make_install
%else
%define cmake_build %__cmake --build "." -j8 --verbose
%define cmake_install DESTDIR=%buildroot %__cmake --install .
%endif
%endif
# undefine macros that may interfere with harbour:
%if %{with harbour}
%undefine vendor
%undefine _vendor
%undefine _chum
%endif
%if 0%{?harbour_validation:1}
BuildRequires: sdk-harbour-rpmvalidator
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -Wno-dev \
    -DQT_IMPORTS_DIR=%{plugindir} \
    -DAPP_FONT_DIR=%{fontdir} \
    -DINSTALL_TESTS=off \
    -DCLICK_MODE=off

%cmake_build

# >> build post
# << build post

%install
# >> install pre
# << install pre
%cmake_install

# >> install post
# set version
sed -i 's/@@UNRELEASED@@/%{version}/' %{buildroot}/%{_datadir}/%{name}/qml/Main.qml

ln -s Main.qml %{buildroot}/%{_datadir}/%{name}/qml/%{name}.qml

# S:1: SVG file for conversion
install -Dpm644 %{S:1} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg

# S:2: TTS Sailjail profile
install -Dpm644 %{S:2} %{buildroot}/%{_sysconfdir}/sailjail/permissions/%{name}.profile


# S:3/4/5: Font files
install -d %{buildroot}/%{fontdir}/Alegreya
install -pm644 %{S:3} %{buildroot}/%{fontdir}/Alegreya/
install -pm644 %{S:4} %{buildroot}/%{fontdir}/Alegreya/
install -d %{buildroot}/%{fontdir}/Fraunces
install -pm644 %{S:5} %{buildroot}/%{fontdir}/Fraunces/

# S:6: Scumming script
install -d %{buildroot}/%{_datadir}/%{name}/_cheat
# harbour will not allow executable in share, so mode 644:
install -pm644 %{S:6} %{buildroot}/%{_datadir}/%{name}/_cheat


# rename default desktop file:
mv %{buildroot}%{_datadir}/applications/lonewolf.desktop %{buildroot}%{_datadir}/applications/%{name}.desktop

desktop-file-edit  \
--set-key=Exec \
--set-value="sailfish-qml %{name}" \
--set-icon=%{name} \
--set-key=X-Nemo-Application-Type \
--set-value=silica-qt5 \
--set-key=X-Nemo-Single-Instance \
--set-value=yes \
--remove-key=X-Ubuntu-Touch \
%{buildroot}%{_datadir}/applications/%{name}.desktop
printf '\n\n[X-Sailjail]\nOrganizationName=%{name}\nApplicationName=%{name}\nPermissions=Audio;WebView;Internet\n' \
>> %{buildroot}%{_datadir}/applications/%{name}.desktop

printf '\n\n[X-HarbourBackup]\nBackupConfigList=/apps/games/lonewolf\nBackupPathList=.cache/%{name}/\n' \
>> %{buildroot}%{_datadir}/applications/%{name}.desktop

# generate some icons
for size in 86 108 128 172 256 512; do
install -d %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
sailfish_svg2png -z 1.0 -f rgba -s 1 1 1 1 1 1 ${size} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/ %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
done
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%check
# >> check
# this is just here so we can include a clean section below:
%clean
%if 0%{?harbour_validation:1}
echo '=========== Checking for Harbour compatability.'
mkdir -p ~/rpmbuild/OTHER || :
find ~/rpmbuild/RPMS -type f -name %{name}-%{version}*.rpm -exec /usr/libexec/sdk-harbour-rpmvalidator/rpmvalidation.sh -d 0 --no-color {}  \; | tee ~/rpmbuild/OTHER/harbour-validator.log ||:
echo '=========== DONE checking for Harbour compatability.'
%else
echo '=========== NOT checking for Harbour compatability.'
%endif
%if 0%{?_chum}
# remove main package, leave TTS Plugin
find ~/rpmbuild/RPMS -type f -name %{name}-%{version}*.rpm -exec rm -f {} \; ||:
find ~/rpmbuild/RPMS -type f -name %{name}-debug*-%{version}*.rpm -exec rm -f {} \; ||:
%endif
%if %{with harbour}
# remove TTS package
find ~/rpmbuild/RPMS -type f -name %{name}-tts-plugin-%{version}*.rpm -exec rm -f {} \; ||:
%endif
# << check

%files
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/*
%{_datadir}/%{name}
%exclude %{_datadir}/%{name}/qml/TTS.qml
# >> files
%if %{with harbour}
%exclude %{_datadir}/icons/*/*/apps/*.svg
%endif
# << files

%files tts-plugin
%{_datadir}/%{name}/qml/TTS.qml
%config %{_sysconfdir}/sailjail/permissions/%{name}.profile
# >> files tts-plugin
# << files tts-plugin
