# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.35.1
# 

Name:       lonewolf

# >> macros
# << macros
%define orgname %{name}
%define appname %{name}
%define pkgname %{name}
%define __provides_exclude ^font..lang=.*$

Summary:    A role-playing choose-your-own-adventure game
Version:    0.1.1.9
Release:    0
Group:      Applications
License:    GPLv3 and OFL
URL:        https://github.com/nephros/lonewolf
Source0:    %{name}-%{version}.tar.gz
Source1:    lonewolf-app-icon.svg
Source2:    lonewolf.profile
Source3:    Alegreya-Medium.otf
Source4:    Alegreya-Regular.otf
Source100:  lonewolf.yaml
Requires:   libsailfishapp-launcher
Requires:   qt5-qtdeclarative-import-Lonewolf
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5XmlPatterns)
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(glesv2)
BuildRequires:  pkgconfig(icu-i18n)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  sailfish-svg2png
BuildRequires:  qml-rpm-macros
BuildRequires:  cmake
BuildRequires:  gettext
BuildRequires:  intltool
BuildRequires:  desktop-file-utils
BuildRequires:  cmake

%description
%{summary}.

Lone Wolf is a role-playing book series from the 80s.

You are the sole survivor of a devastating attack on the monastery where
you were learning the skills of the Kai Lords. You swear vengeance on the
Darklords for the massacre of the Kai warriors, and with a sudden flash of
insight you know what you must do. You must set off on a perilous journey
to the capital city to warn the King of the terrible threat that faces his
people: For you are now the last of the Kai.

You are now Lone Wolf.

This App is a port of Tim Süberkrüb's Qt/QML version, which is a port of
the original Lone Wolf app for Ubuntu Phone by Michael Terry.

%if "0%{?_chum}"
Title: Lonewolf
Type: desktop-application
DeveloperName: Peter G., Tim Süberkrüb, Michael Terry
PackagedBy: nephros
Categories:
 - Games
Custom:
  Repo: https://github.com/nephros/lonewolf
PackageIcon: %{url}/raw/sfos/rpm/lonewolf-app-icon.svg
Screenshots:
  - %{url}/raw/sfos/Screenshot_001.jpg
  - %{url}/raw/sfos/Screenshot_002.jpg
Links:
  Help: https://www.projectaon.org/en/ReadersHandbook/Home
%endif


%package -n qt5-qtdeclarative-import-Lonewolf
Summary:    Lonewolf player QML plugin
Group:      Libraries

%description -n qt5-qtdeclarative-import-Lonewolf
%{summary}.

%package tts-plugin
Summary:    Text-to-Speech support for %{name}
Group:      Games
Requires:   %{name} = %{version}-%{release}
Requires:   harbour-dsnote >= 4.7.0

%description tts-plugin
Adds text-to-speech support to the Lonewolf player.

Requires the excellent Speech Note (harbour-dsnote) by mkiol, and
will use its engine and settings configured for English.

%if "0%{?_chum}"
Title: TTS plugin for Lonewolf
Type: desktop-application
Categories:
 - Games
PackageIcon: %{url}/raw/sfos/rpm/lonewolf-app-icon.svg
%endif


%define please_ignore this macro
%if 0%{?sailfishos_version} < 40600
%define cmake_build %__cmake --build "." -j8 --verbose
%define cmake_install DESTDIR=%buildroot %__cmake --install .
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DQT_IMPORTS_DIR=%{_libdir}/qt5/qml \
    -DLONEWOLF_DIR=%{_datadir}/%{name} \
    -DINSTALL_TESTS=off \
    -DCLICK_MODE=off

%cmake_build

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%cmake_install

# >> install post
ln -s Main.qml %{buildroot}/%{_datadir}/%{name}/qml/%{name}.qml

# S:1: SVG file for conversion
install -Dpm644 %{S:1} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg

# S:2: TTS Sailjail profile
install -Dpm644 %{S:2} %{buildroot}/%{_sysconfdir}/sailjail/permissions/%{name}.profile


# S:3/4: Font files
install -d %{buildroot}/%{_datadir}/fonts/%{name}/
install -pm644 %{S:3} %{buildroot}/%{_datadir}/fonts/%{name}/
install -pm644 %{S:4} %{buildroot}/%{_datadir}/fonts/%{name}/

desktop-file-edit  \
--set-key=Exec \
--set-value="/usr/bin/invoker --single-instance --type=silica-qt5 /usr/bin/sailfish-qml lonewolf" \
--set-key=X-Nemo-Application-Type \
--set-value=silica-qt5 \
--remove-key=X-Ubuntu-Touch \
%{buildroot}%{_datadir}/applications/%{name}.desktop
printf '\n\n[X-Sailjail]\nOrganizationName=%{name}\nApplicationName=%{name}\nPermissions=Audio;WebView;Internet\n' \
>> %{buildroot}%{_datadir}/applications/%{name}.desktop

printf '\n\n[X-HarbourBackup]\nBackupConfigList=/apps/games/lonewolf\nBackupPathList=.cache/lonewolf/\n'
>> %{buildroot}%{_datadir}/applications/%{name}.desktop

# generate some icons
for size in 86 108 128 172 256 512; do
install -d %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
sailfish_svg2png -z 1.0 -f rgba -s 1 1 1 1 1 1 ${size} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/ %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
done
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/%{name}.png
%{_datadir}/icons/*/*/apps/%{name}.svg
%{_datadir}/%{name}
%dir %{_datadir}/fonts/%{name}
%{_datadir}/fonts/%{name}/*
%exclude %{_datadir}/%{name}/qml/TTS.qml
# >> files
# << files

%files -n qt5-qtdeclarative-import-Lonewolf
%defattr(-,root,root,-)
%{_libdir}/qt5/qml/Lonewolf/
# >> files qt5-qtdeclarative-import-Lonewolf
# << files qt5-qtdeclarative-import-Lonewolf

%files tts-plugin
%defattr(-,root,root,-)
%{_datadir}/%{name}/qml/TTS.qml
%{_sysconfdir}/sailjail/permissions/%{name}.profile
# >> files tts-plugin
# << files tts-plugin
