# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.35.1
# 

Name:       lonewolf

# >> macros
%bcond_with harbour
# << macros
%define orgname %{name}
%define appname %{name}
%define pkgname %{name}

Summary:    The Lone Wolf Adventures
Version:    0.1.1
Release:    0
Group:      Applications
License:    GPLv3
URL:        https://github.com/timsueberkrueb/lonewolf
Source0:    %{name}-%{version}.tar.gz
Source1:    lonewolf-bighead.png
Source2:    lonewolf-app-icon.svg
Source100:  lonewolf.yaml
Patch0:     SailfishOS-build.patch
Patch1:     SailfishOS-qml-1.patch
Patch2:     SailfishOS-qml-2.patch
Requires:   libsailfishapp-launcher
Requires:   qt5-qtdeclarative-import-Lonewolf
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5XmlPatterns)
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(glesv2)
BuildRequires:  pkgconfig(icu-i18n)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  sailfish-svg2png
BuildRequires:  qml-rpm-macros
BuildRequires:  cmake
BuildRequires:  gettext
BuildRequires:  intltool
BuildRequires:  desktop-file-utils
BuildRequires:  cmake

%description
%{summary}.

Lone Wolf is a role-playing book series from the 80s.

You are the sole survivor of a devastating attack on the monastery where
you were learning the skills of the Kai Lords. You swear vengeance on the
Darklords for the massacre of the Kai warriors, and with a sudden flash of
insight you know what you must do. You must set off on a perilous journey
to the capital city to warn the King of the terrible threat that faces his
people: For you are now the last of the Kai.

You are now Lone Wolf.

%if "%{?vendor}" == "chum"
Title: Lonewolf
Type: desktop-application
PackagedBy: nephros
Categories:
 - Games
Custom:
  Repo: %{url}
  PackagingRepo: https://github.com/nephros/lonewolf
PackageIcon: https://www.projectaon.org/en/images/logotop.gif
Links:
  Homepage: https://www.projectaon.org/
  Help: https://www.projectaon.org/en/ReadersHandbook/Home
%endif


%package -n qt5-qtdeclarative-import-Lonewolf
Summary:    Lonewolf player for QML
Group:      Libraries

%description -n qt5-qtdeclarative-import-Lonewolf
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# SailfishOS-build.patch
%patch0 -p1
# SailfishOS-qml-1.patch
%patch1 -p1
# SailfishOS-qml-2.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DQT_IMPORTS_DIR=%{_libdir}/qt5/qml \
    -DLONEWOLF_DIR=%{_datadir}/%{name} \
    -DINSTALL_TESTS=off \
    -DCLICK_MODE=off

%cmake_build

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%cmake_install

# >> install post
ln -s Main.qml %{buildroot}/%{_datadir}/%{name}/qml/%{name}.qml
install -pm644 %{S:1} %{buildroot}/%{_datadir}/%{name}/qml/
#install -Dpm644 app/graphics/%%{name}.png %%{buildroot}/%%{_datadir}/icons/hicolor/256x256/apps/%%{name}.png

desktop-file-edit  \
--set-key=X-Nemo-Application-Type \
--set-value=silica-qt5 \
%{buildroot}%{_datadir}/applications/%{name}.desktop
printf '\n\n[X-Sailjail]\nOrganizationName=%{name}\nApplicationName=%{name}\nPermissions=WebView;Internet\n' \
>> %{buildroot}%{_datadir}/applications/%{name}.desktop

# generate some icons
install -Dpm644 %{S:2} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg
for size in 86 108 128 172 256 512; do
install -d %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
sailfish_svg2png -z 1.0 -f rgba -s 1 1 1 1 1 1 ${size} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/ %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
done


# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/%{name}.png
%{_datadir}/icons/*/*/apps/%{name}.svg
%{_datadir}/%{name}
# >> files
# << files

%files -n qt5-qtdeclarative-import-Lonewolf
%defattr(-,root,root,-)
%{_libdir}/qt5/qml/Lonewolf/
# >> files qt5-qtdeclarative-import-Lonewolf
# << files qt5-qtdeclarative-import-Lonewolf
